### ISSUE TITLE
Multiple dex files define during build. fix included

### ISSUE THREAD

**Issue by kobruleht** [xuxingliu922/DeviceSDK#2]
According to 

http://stackoverflow.com/questions/36103262/how-to-fix-android-multiple-dex-files-define-exception/36103571#36103571

Its buid causes exception

UNEXPECTED TOP-LEVEL EXCEPTION: com.android.dex.DexException: Multiple dex files define Landroid/support/v4/accessibilityservice/AccessibilityServiceInfoCompat$AccessibilityServiceInfoVersionImpl;

Solution from there:

It happens becuase you are adding twice the same class.

you are using:

dependencies {
    compile fileTree(dir: 'libs', include: '*.jar')
    compile 'com.android.support:appcompat-v7:23.1.1'
}

The appcompat has a dependency with the support-v4.
You have the android-support-v4.jar in your libs folders.
Remove it.

**Comment by cricket007** [comment]
@kobruleht You can submit a pull request to delete the relevant pieces.
